# Data source definition
data_source:
  type: 'CSV'
  parameters:
    tables:
      ship_types: 'data/ship_types.csv'
      ships: 'data/ships.csv'
      locations: 'data/locations.csv'
      
# Map configuration
basemap:
  url: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  attribution: "Appsilon"
  center:
    latitude: 52.23276982545444
    longitude: 21.01414467671963
  zoom: 20
